### ISSUE TITLE
The getter 'offset' was called on null

### ISSUE THREAD

**Issue by brizaldi** [RafaelBarbosatec/tutorial_coach_mark#34]
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during paint():
The getter 'offset' was called on null.
Receiver: null
Tried calling: offset

package:tutorial_coach_mark/light_paint_rect.dart:33:55

**Comment by niypoo** [comment]
me too after updated from 0.3 to 0.5 I'm facing this issue so I have downgraded to 0.3 again

**Comment by RafaelBarbosatec** [comment]
I'll be analyzing ... Thanks for the issue

**Comment by RafaelBarbosatec** [comment]
Fix available in version 0.5.1.

**Comment by ibrahim-mubarak** [comment]
I still have this issue in 0.5.1
We are doing a multi page Tutorial
The error pops up when opening a new page

**Comment by mono0926** [comment]
@ibrahim-mubarak 

By specifying this at `pubspec.yaml`, it may be fixed:

```yaml
  tutorial_coach_mark:
    git:
      url: https://github.com/mono0926/tutorial_coach_mark.git
      ref: fix-34
```
